"use client";
import { useEffect, useState, type FormEvent } from "react";
import Link from "next/link";
import { apiFetch, refreshSession, requireOk, getStoredUser } from "../../lib/session";
type Member={userId:string;phone:string;name:string|null;role:string;active:boolean;channelIds:string[]|null;workflowIds:string[]|null};
type Item={id:string;name?:string;displayName?:string|null;channel?:string};
type Team={members:Member[];channels:Item[];workflows:Item[]};
export default function TeamPage(){
 const [team,setTeam]=useState<Team|null>(null);const [allowed,setAllowed]=useState(false);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [editing,setEditing]=useState<string|null>(null);const [phone,setPhone]=useState("");const [name,setName]=useState("");const [password,setPassword]=useState("");const [role,setRole]=useState("editor");const [active,setActive]=useState(true);const [channels,setChannels]=useState<string[]|null>(null);const [workflows,setWorkflows]=useState<string[]|null>(null);
 const load=async()=>setTeam(await requireOk(await apiFetch("/team"),"دریافت اعضا انجام نشد."));
 useEffect(()=>{void refreshSession().then(session=>{if(!["manager","owner"].includes(session.membership?.role??"")){setMessage("مدیریت اعضا فقط برای مدیر سازمان در دسترس است.");return;}setAllowed(true);return load();}).catch(error=>setMessage(error.message));},[]);
 const select=(member?:Member)=>{setEditing(member?.userId??null);setPhone(member?.phone??"");setName(member?.name??"");setPassword("");setRole(member?.role??"editor");setActive(member?.active??true);setChannels(member?.channelIds??null);setWorkflows(member?.workflowIds??null);};
 const save=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setMessage("");try{await requireOk(await apiFetch(editing?`/team/${editing}`:"/team",{method:editing?"PATCH":"POST",body:JSON.stringify({phone,...(!editing||name!==team?.members.find(member=>member.userId===editing)?.name?{name}:{}),role,active,channelIds:role==="manager"?null:channels,workflowIds:role==="manager"?null:workflows,...(password?{password}:{})})}),"ذخیره عضو انجام نشد؛ شماره، رمز و دسترسی‌ها را بررسی کنید.");setPassword("");await load();select();setMessage("عضو و دسترسی‌های او ذخیره شد.");}catch(error){setMessage(error instanceof Error?error.message:"ذخیره انجام نشد.");}finally{setBusy(false);}};
 const scope=(title:string,items:Item[],selected:string[]|null,setSelected:(value:string[]|null)=>void)=><fieldset><legend>{title}</legend><label><input type="checkbox" checked={selected===null} onChange={event=>setSelected(event.target.checked?null:[])}/>دسترسی به همه</label>{selected!==null?items.map(item=><label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={event=>setSelected(event.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/>{item.name??item.displayName??item.channel??"بدون عنوان"}</label>):null}<small>{selected===null?"شامل مواردی که بعداً اضافه می‌شوند.":selected.length?`${selected.length.toLocaleString("fa-IR")} مورد انتخاب شده` :"هیچ موردی مجاز نیست."}</small></fieldset>;
 return <main className="settings-page"><Link href="/">← میز کار</Link><h1>اعضای سازمان</h1><p>مدیر سامانه به اطلاعات کانال‌ها، جریان‌ها و فعالیت دسترسی دارد؛ مشاهده او ثبت می‌شود.</p>{message?<p role="status">{message}</p>:null}{allowed?<><section className="settings-card"><h2>اعضا و دسترسی‌ها</h2>{team?.members.map(member=><article key={member.userId}><strong>{member.name||member.phone}</strong><span> · {member.role==="manager"?"مدیر":"عضو"} · {member.active?"فعال":"غیرفعال"}</span><button className="ghost-button" disabled={busy||member.userId===getStoredUser()?.id} onClick={()=>select(member)}>ویرایش</button></article>)}</section><section className="settings-card"><h2>{editing?"ویرایش عضو":"افزودن عضو"}</h2><form className="auth-form" onSubmit={save}>
 <label><span>شماره همراه</span><input dir="ltr" inputMode="tel" autoComplete="off" required disabled={Boolean(editing)} value={phone} onChange={e=>setPhone(e.target.value)}/></label><label><span>نام</span><input required value={name} onChange={e=>setName(e.target.value)}/></label>
 <label><span>{editing?"رمز جدید، برای حفظ رمز خالی بگذارید":"رمز عبور اولیه"}</span><input dir="ltr" type="password" autoComplete="new-password" minLength={10} maxLength={128} required={!editing} value={password} onChange={e=>setPassword(e.target.value)}/></label><small>کاربر هنگام اولین ورود یا پس از تعیین رمز جدید، باید رمز را تغییر دهد.</small>
 <label><span>نقش</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="editor">ویرایشگر محتوا</option><option value="reviewer">بازبین محتوا</option><option value="publisher">مسئول انتشار</option><option value="viewer">مشاهده‌گر</option><option value="manager">مدیر سازمان</option></select></label>{editing?<label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>حساب فعال</label>:null}
 {scope("کانال‌های مجاز",team?.channels??[],channels,setChannels)}{scope("جریان‌های مجاز",team?.workflows??[],workflows,setWorkflows)}<small>مدیر سازمان به تمام اعضا، کانال‌ها و جریان‌های سازمان دسترسی دارد.</small>
 <div><button className="primary-button" disabled={busy}>{busy?"در حال ذخیره…":"ذخیره عضو"}</button>{editing?<button type="button" className="ghost-button" onClick={()=>select()}>انصراف از ویرایش</button>:null}</div></form></section></>:null}</main>;
}
