import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';import Fastify from 'fastify';import {PGlite} from '@electric-sql/pglite';import {drizzle} from 'drizzle-orm/pglite';import * as tables from '@socialyar/db/schema';import {getDb} from '@socialyar/db';import {authPlugin} from './auth';
const engine=new PGlite(),db=drizzle(engine,{schema:tables}),app=Fastify();const userId=randomUUID(),workspaceId=randomUUID(),allowedFlow=randomUUID(),deniedFlow=randomUUID(),accountId=randomUUID();let token='';const calendar:any[]=[],youtube:any[]=[],reviews:any[]=[];
before(async()=>{
 process.env.JWT_SECRET='scope-integration-test-secret-at-least-32';for(const name of ['0000_initial.sql','0001_auth.sql','0002_eitaa_automation.sql','0006_youtube.sql','0008_publication_calendar.sql','0011_execution_recovery.sql','0012_tenant_access.sql'])await engine.exec(await readFile(new URL(`../../../packages/db/migrations/${name}`,import.meta.url),'utf8'));
 await db.insert(tables.users).values({id:userId,email:'scoped@example.com'});const ownerId=randomUUID();await db.insert(tables.users).values({id:ownerId,email:'scope-owner@example.com'});await db.insert(tables.workspaces).values({id:workspaceId,ownerId,name:'scope',slug:'scope-response'});await db.insert(tables.workspaceMembers).values({workspaceId,userId,role:'reviewer',channelIds:[accountId],workflowIds:[allowedFlow]});await db.insert(tables.workspaceSubscriptions).values({workspaceId});await db.insert(tables.socialAccounts).values({id:accountId,workspaceId,channel:'youtube',externalAccountId:'scope-channel'});
 for(const [flow,secret] of [[allowedFlow,'ALLOWED'],[deniedFlow,'FORBIDDEN']] as const){const version=randomUUID(),run=randomUUID();await db.insert(tables.workflows).values({id:flow,workspaceId,name:secret});await db.insert(tables.workflowVersions).values({id:version,workflowId:flow,version:1});await db.insert(tables.runs).values({id:run,workflowId:flow,workflowVersionId:version,status:'waiting_approval'});reviews.push({runId:run,output:{text:secret}});
 const [content]=await db.insert(tables.contentItems).values({workspaceId,runId:run,body:secret}).returning();const [variant]=await db.insert(tables.contentVariants).values({contentItemId:content.id,channel:'youtube',body:secret,status:'waiting_approval',settings:{accountId}}).returning();calendar.push({kind:'variant',sourceId:variant.id,body:secret});
 const [video]=await db.insert(tables.youtubeItems).values({workspaceId,workflowId:flow,runId:run,accountId,stepKey:"youtube",itemKey:secret,title:secret,description:secret,channelName:'scope',status:'waiting_approval'}).returning();youtube.push({id:video.id,title:secret});}
 await authPlugin(app,{db:db as unknown as ReturnType<typeof getDb>});for(const [url,data] of [['/calendar/items',calendar],['/youtube/items',youtube],['/workflow-approvals',reviews]] as const)app.get(url,{onRequest:[app.authenticate]},async()=>data);token=app.signAccessToken({sub:userId,email:'scoped@example.com',workspaceId,sessionVersion:0});
});after(async()=>{await app.close();await engine.close();});
for(const url of ['/calendar/items','/youtube/items','/workflow-approvals'])test(`real JWT response hook filters unauthorized rows from ${url}`,async()=>{const response=await app.inject({method:'GET',url,headers:{authorization:`Bearer ${token}`}});assert.equal(response.statusCode,200,response.body);assert.equal(response.json().length,1,response.body);assert.ok(response.body.includes('ALLOWED'),response.body);assert.ok(!response.body.includes('FORBIDDEN'),response.body);});
