"use client";
import { statusLabel } from "../lib/persian";
import Link from "next/link";
import { useEffect, useState, useRef, type FormEvent } from "react";
import { localParts, wallTimeToUTC } from "../lib/persian-calendar";
import { apiFetch, refreshSession, requireOk } from "../lib/session";
type Subscription={status:string;plan:string;expiresAt:string|null;maxUsers:number|null;maxChannels:number|null;maxWorkflows:number|null;aiTokenLimit:number|null;aiTokensUsed:number;aiTokensReserved?:number};
type Organization={id:string;name:string;slug:string;subscription:Subscription|null};
type Activity={channels:Array<{id:string;channel:string;displayName:string|null}>;workflows:Array<{id:string;name:string;status:string}>;activity:Array<{id:string;action?:string;type?:string;actorId?:string;createdAt:string}>;runs:Array<{id:string;status:string;workflowId:string;createdAt:string}>;usage:{inputTokens:number;outputTokens:number;costMicros:number}};
const defaultSubscription:Subscription={status:"active",plan:"standard",expiresAt:null,maxUsers:10,maxChannels:10,maxWorkflows:20,aiTokenLimit:1000000,aiTokensUsed:0};
function expiryInput(value:string|null){if(!value)return "";const p=localParts(new Date(value),"Asia/Tehran");return `${p.year}-${String(p.month).padStart(2,"0")}-${String(p.day).padStart(2,"0")}T${String(p.hour).padStart(2,"0")}:${String(p.minute).padStart(2,"0")}`;}
export default function PlatformPage(){
 const inspectGeneration=useRef(0);
 const [allowed,setAllowed]=useState(false);const [organizations,setOrganizations]=useState<Organization[]>([]);const [selected,setSelected]=useState<Organization|null>(null);const [activity,setActivity]=useState<Activity|null>(null);const [subscription,setSubscription]=useState<Subscription>(defaultSubscription);const [name,setName]=useState("");const [slug,setSlug]=useState("");const [managerPhone,setPhone]=useState("");const [managerName,setManagerName]=useState("");const [managerPassword,setPassword]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const load=async()=>{const data=await requireOk(await apiFetch("/platform/workspaces"),"دریافت سازمان‌ها انجام نشد.");setOrganizations(data.workspaces);};
 useEffect(()=>{void refreshSession().then(session=>{if(!session.user.isPlatformAdmin){setMessage("این صفحه فقط برای مدیر سامانه در دسترس است.");return;}setAllowed(true);return load();}).catch(error=>setMessage(error.message));},[]);
 const create=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setMessage("");try{await requireOk(await apiFetch("/platform/workspaces",{method:"POST",body:JSON.stringify({name,slug,managerPhone,managerName,managerPassword})}),"ساخت سازمان انجام نشد؛ شناسه سازمان، شماره همراه و رمز مدیر را بررسی کنید.");setName("");setSlug("");setPhone("");setManagerName("");setPassword("");await load();setMessage("سازمان و حساب مدیر ساخته شدند؛ مدیر باید در اولین ورود رمز را تغییر دهد.");}catch(error){setMessage(error instanceof Error?error.message:"ساخت سازمان انجام نشد.");}finally{setBusy(false);}};
 const inspect=async(organization:Organization)=>{const generation=++inspectGeneration.current;setSelected(organization);setSubscription({...defaultSubscription,...organization.subscription});setActivity(null);setBusy(true);setMessage("");try{const data=await requireOk(await apiFetch(`/platform/workspaces/${organization.id}/activity`),"دریافت فعالیت سازمان انجام نشد.");if(generation===inspectGeneration.current)setActivity(data);}catch(error){if(generation===inspectGeneration.current)setMessage(error instanceof Error?error.message:"دریافت فعالیت انجام نشد.");}finally{if(generation===inspectGeneration.current)setBusy(false);}};
 const saveSubscription=async(event:FormEvent)=>{event.preventDefault();if(!selected)return;setBusy(true);setMessage("");try{await requireOk(await apiFetch(`/platform/workspaces/${selected.id}`,{method:"PATCH",body:JSON.stringify({plan:subscription.plan,status:subscription.status,expiresAt:subscription.expiresAt,maxUsers:subscription.maxUsers,maxChannels:subscription.maxChannels,maxWorkflows:subscription.maxWorkflows,aiTokenLimit:subscription.aiTokenLimit})}),"ذخیره اشتراک انجام نشد؛ ظرفیت‌ها و تاریخ را بررسی کنید.");await load();setMessage("اشتراک سازمان ذخیره شد.");}catch(error){setMessage(error instanceof Error?error.message:"ذخیره اشتراک انجام نشد.");}finally{setBusy(false);}};
 return <main className="settings-page"><Link href="/">← میز کار</Link><h1>مدیریت سامانه هور+</h1><p>مدیر سامانه می‌تواند کانال‌ها، جریان‌ها، وضعیت اجرا و مصرف سازمان‌ها را برای پشتیبانی و مدیریت اشتراک مشاهده کند. مشاهده و تغییر اطلاعات در گزارش مدیریتی ثبت می‌شود.</p>{message?<p role="status">{message}</p>:null}{allowed?<><section className="settings-card"><h2>سازمان‌ها</h2>{organizations.map(organization=><article key={organization.id}><strong>{organization.name}</strong><small> · {organization.slug}</small><button className="ghost-button" disabled={busy} onClick={()=>void inspect(organization)}>اشتراک و فعالیت</button></article>)}</section>
 <section className="settings-card"><h2>ساخت سازمان</h2><form className="auth-form" onSubmit={create}><label><span>نام سازمان</span><input required value={name} onChange={e=>setName(e.target.value)}/></label><label><span>شناسه سازمان، حروف انگلیسی و خط تیره</span><input required dir="ltr" pattern="[a-z0-9-]+" value={slug} onChange={e=>setSlug(e.target.value)}/></label><label><span>نام مدیر سازمان</span><input required value={managerName} onChange={e=>setManagerName(e.target.value)}/></label><label><span>شماره همراه مدیر</span><input required dir="ltr" inputMode="tel" value={managerPhone} onChange={e=>setPhone(e.target.value)}/></label><label><span>رمز اولیه مدیر، حداقل ۱۰ نویسه</span><input required minLength={10} maxLength={128} dir="ltr" type="password" autoComplete="new-password" value={managerPassword} onChange={e=>setPassword(e.target.value)}/></label><button className="primary-button" disabled={busy}>{busy?"در حال ذخیره…":"ساخت سازمان و حساب مدیر"}</button></form></section>
 {selected?<><section className="settings-card"><h2>اشتراک {selected.name}</h2><p>مصرف اعتبار AI: {subscription.aiTokensUsed.toLocaleString("fa-IR")} توکن · اعتبار رزروشده: {(subscription.aiTokensReserved??0).toLocaleString("fa-IR")} توکن</p><form className="auth-form" onSubmit={saveSubscription}><label><span>طرح اشتراک</span><input required dir="ltr" value={subscription.plan} onChange={e=>setSubscription({...subscription,plan:e.target.value})}/></label><label><span>وضعیت</span><select value={subscription.status} onChange={e=>setSubscription({...subscription,status:e.target.value})}><option value="active">فعال</option><option value="suspended">تعلیق‌شده</option><option value="cancelled">لغوشده</option><option value="expired">پایان‌یافته</option></select></label><label><span>پایان اشتراک، تاریخ میلادی و ساعت به وقت تهران؛ خالی یعنی بدون پایان</span><input type="datetime-local" dir="ltr" value={expiryInput(subscription.expiresAt)} onChange={e=>setSubscription({...subscription,expiresAt:e.target.value?wallTimeToUTC(new Date(`${e.target.value.slice(0,10)}T12:00:00Z`),Number(e.target.value.slice(11,13)),Number(e.target.value.slice(14,16)),"Asia/Tehran").toISOString():null})}/></label>
 {([["maxUsers","ظرفیت کاربران"],["maxChannels","ظرفیت کانال‌ها"],["maxWorkflows","ظرفیت جریان‌های فعال"],["aiTokenLimit","سقف توکن هوش مصنوعی"]] as const).map(([key,label])=><label key={key}><span>{label}</span><input type="number" min={key==="maxUsers"?1:0} placeholder="بدون محدودیت" value={subscription[key]??""} onChange={e=>setSubscription({...subscription,[key]:e.target.value===""?null:Number(e.target.value)})}/><small>خالی یعنی بدون محدودیت.</small></label>)}<button className="primary-button" disabled={busy}>ذخیره اشتراک</button></form></section>
 <section className="settings-card"><h2>فعالیت {selected.name}</h2>{activity?<><p>{activity.channels.length.toLocaleString("fa-IR")} کانال · {activity.workflows.length.toLocaleString("fa-IR")} جریان</p><p>توکن ورودی: {activity.usage.inputTokens.toLocaleString("fa-IR")} · خروجی: {activity.usage.outputTokens.toLocaleString("fa-IR")}</p><h3>کانال‌ها</h3>{activity.channels.map(channel=><p key={channel.id}>{channel.displayName??channel.channel}</p>)}<h3>جریان‌ها</h3>{activity.workflows.map(workflow=><p key={workflow.id}>{workflow.name} · {({active:"فعال",draft:"پیش‌نویس",paused:"متوقف‌شده",archived:"بایگانی‌شده",inactive:"غیرفعال"} as Record<string,string>)[workflow.status]??statusLabel(workflow.status)}</p>)}<h3>آخرین اجراها</h3>{activity.runs.map(run=><p key={run.id}>{activity.workflows.find(workflow=>workflow.id===run.workflowId)?.name??"اجرای جریان"} · {statusLabel(run.status)} · {new Date(run.createdAt).toLocaleString("fa-IR",{timeZone:"Asia/Tehran"})}</p>)}<h3>آخرین فعالیت‌ها</h3>{activity.activity.map(item=><p key={item.id}>{({"team.member_created":"افزودن عضو", "team.member_updated":"تغییر عضو و دسترسی‌ها", "platform.workspace_created":"ساخت سازمان", "platform.subscription_updated":"تغییر اشتراک", "platform.workspaces_viewed":"مشاهده فهرست سازمان‌ها توسط مدیر سامانه", "platform.workspace_activity_viewed":"مشاهده فعالیت سازمان توسط مدیر سامانه", "auth.password_changed":"تغییر رمز حساب", "auth.workspace_switched":"تغییر سازمان فعال", run_started:"شروع اجرا",run_completed:"پایان پردازش",run_failed:"اجرای ناموفق",step_completed:"مرحله انجام شد",step_failed:"خطای مرحله",approval_requested:"در انتظار تأیید",approval_resolved:"ثبت تصمیم"} as Record<string,string>)[item.type??item.action??""]??"فعالیت ثبت‌شده"} · {new Date(item.createdAt).toLocaleString("fa-IR",{timeZone:"Asia/Tehran"})}</p>)}{!activity.activity.length?<p>فعالیتی ثبت نشده است.</p>:null}</>:<p>{busy?"در حال دریافت فعالیت…":"فعالیت سازمان در دسترس نیست."}</p>}</section></>:null}</>:null}</main>;
}
